name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: setup visual studio environment
      uses: ilammy/msvc-dev-cmd@v1

    - name: install ninja
      run: choco install ninja

    - name: create build directory
      run: mkdir build

    - name: configure CMake
      run: |
        cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release

    - name: build
      run: cmake --build build --config Release

    - name: prepare artifacts
      run: |
        mkdir artifacts
        cp build/*.exe artifacts/ || echo "No exe files found in root build dir"
        cp build/*.pdb artifacts/ || echo "No pdb files found in root build dir"
        cp build/src/*.exe artifacts/ || echo "No exe files found in src build dir"
        cp build/src/*.pdb artifacts/ || echo "No pdb files found in src build dir"

#    - name: create release
#      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
#      id: create_release
#      uses: softprops/action-gh-release@v1
#      with:
#        name: Release ${{ github.sha }}
#        tag_name: v${{ github.run_number }}
#        files: artifacts/*
#        generate_release_notes: true
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}